workflow: research
asset_types: [vn_stock]

universe: vn100

start_date: "2018-01-01"
end_date: "2026-05-31"
validation:
  method: multi_interval
  test_intervals:
    - start_date: "2021-01-01"
      end_date: "2023-01-01"
    - start_date: "2024-01-01"
      end_date: "2026-05-30"
initial_capital: 100000000

data_sources:
  vn_stock: vnstock
storage: duckdb
features:
  transforms:
    - name: average_price
      params:
        output_column: avg_price

    - name: log_volume
      params:
        volume_column: volume
        output_column: log_volume

    - name: log_price
      params:
        price_column: avg_price
        output_column: log_price

    - name: ml_factor_target_class
      params:
        target_column: forward_return_{rebalance_period}
        output_column: forward_return_{rebalance_period}_class

    # - name: qsmom
    #   params:
    #     close_column: log_price
    #     roc_fast_period: 21
    #     roc_slow_period: 252
    #     returns_period: 126

  indicators:
    - name: rsi
      params:
        periods: [14, 21]
        price_column: log_price

    - name: roc
      params:
        periods: [14, 21]
        price_column: log_price

    - name: ma
      params:
        periods: [5, 10, 20]
        price_column: log_price

    - name: adx
      params:
        periods: [14, 21]

    - name: volume_ratio
      params:
        volume_column: log_volume
        windows: [5, 12]

    - name: hist_vol
      params:
        price_column: log_price
        windows: [21, 42]

    - name: zscore
      params:
        windows: [10, 21, 42]

strategy:
  type: ml_factor
  params:
    task: classification
    cv_splits: 5
    cv_gap: 12
    cv_test_size: 12

rebalance_frequency: 10
portfolio_construction:
  name: equal_weight
  params:
    num_long_positions: [5, 8, 10]
    num_short_positions: 0

backtest_engine: vectorbt
train_window: 252  # 252 * 3

commission:
  model: percentage
  rate: 0.0015

benchmark: "VN:VNINDEX"
