name: binance_crypto_futures
asset_type: crypto_futures
description: "Current Binance USDT-M perpetual futures with first daily kline on or before 2022-01-01."
benchmark_symbol: "PERP:BTC/USDT"
symbols:
  - "PERP:1000SHIB/USDT"
  - "PERP:1000XEC/USDT"
  - "PERP:1INCH/USDT"
  - "PERP:AAVE/USDT"
  - "PERP:ADA/USDT"
  - "PERP:ALGO/USDT"
  - "PERP:ALICE/USDT"
  - "PERP:ANKR/USDT"
  - "PERP:AR/USDT"
  - "PERP:ARPA/USDT"
  - "PERP:ATOM/USDT"
  - "PERP:AVAX/USDT"
  - "PERP:AXS/USDT"
  - "PERP:BAND/USDT"
  - "PERP:BAT/USDT"
  - "PERP:BCH/USDT"
  - "PERP:BEL/USDT"
  - "PERP:BNB/USDT"
  - "PERP:BTC/USDT"
  - "PERP:BTCDOM/USDT"
  - "PERP:C98/USDT"
  - "PERP:CELO/USDT"
  - "PERP:CELR/USDT"
  - "PERP:CHR/USDT"
  - "PERP:CHZ/USDT"
  - "PERP:COMP/USDT"
  - "PERP:COTI/USDT"
  - "PERP:CRV/USDT"
  - "PERP:CTSI/USDT"
  - "PERP:DASH/USDT"
  - "PERP:DOGE/USDT"
  - "PERP:DOT/USDT"
  - "PERP:DYDX/USDT"
  - "PERP:EGLD/USDT"
  - "PERP:ENJ/USDT"
  - "PERP:ENS/USDT"
  - "PERP:ETC/USDT"
  - "PERP:ETH/USDT"
  - "PERP:FIL/USDT"
  - "PERP:GALA/USDT"
  - "PERP:GRT/USDT"
  - "PERP:GTC/USDT"
  - "PERP:HBAR/USDT"
  - "PERP:HOT/USDT"
  - "PERP:ICX/USDT"
  - "PERP:IOST/USDT"
  - "PERP:IOTA/USDT"
  - "PERP:IOTX/USDT"
  - "PERP:KAVA/USDT"
  - "PERP:KNC/USDT"
  - "PERP:KSM/USDT"
  - "PERP:LINK/USDT"
  - "PERP:LPT/USDT"
  - "PERP:LTC/USDT"
  - "PERP:MANA/USDT"
  - "PERP:MASK/USDT"
  - "PERP:MTL/USDT"
  - "PERP:NEAR/USDT"
  - "PERP:NEO/USDT"
  - "PERP:OGN/USDT"
  - "PERP:ONE/USDT"
  - "PERP:ONT/USDT"
  - "PERP:PEOPLE/USDT"
  - "PERP:QTUM/USDT"
  - "PERP:RLC/USDT"
  - "PERP:ROSE/USDT"
  - "PERP:RSR/USDT"
  - "PERP:RUNE/USDT"
  - "PERP:RVN/USDT"
  - "PERP:SAND/USDT"
  - "PERP:SFP/USDT"
  - "PERP:SKL/USDT"
  - "PERP:SNX/USDT"
  - "PERP:SOL/USDT"
  - "PERP:STORJ/USDT"
  - "PERP:SUSHI/USDT"
  - "PERP:THETA/USDT"
  - "PERP:TRB/USDT"
  - "PERP:TRX/USDT"
  - "PERP:UNI/USDT"
  - "PERP:VET/USDT"
  - "PERP:XLM/USDT"
  - "PERP:XMR/USDT"
  - "PERP:XRP/USDT"
  - "PERP:XTZ/USDT"
  - "PERP:YFI/USDT"
  - "PERP:ZEC/USDT"
  - "PERP:ZEN/USDT"
  - "PERP:ZIL/USDT"
  - "PERP:ZRX/USDT"
